Feature/map places
niestierov/NearestPlaces pull request #1
Opened 2023-11-10 12:41 UTC by niestierov

2023-11-13 14:10 UTC, Nikitax23 requested changes
Непогана робота! 
Повиправляй коменти, та ще раз подивимось, що ще можна покращити. 

Примітка:

2023-11-13 14:10 UTC, Nikitax23 commented on NearestPlaces/App&SceneDelegate/AppDelegate.swift
> +        if let apiKey = Bundle.main.object(forInfoDictionaryKey: AppConstant.apiKeyGoogle) as? String {
Це треба винести у окремий сервіс (нехай він буде GoogleMapsConfigurator або GoogleServicesConfigurator, який буде мати всього один метод configure , і не буде поширювати ніякі деталі на верхні шари.

Тобто з AppDelegate ми приберемо таким чином import GoogleMaps , і просто звернемось googleServicesConfigurator.configure()

2023-11-13 14:10 UTC, Nikitax23 commented on NearestPlaces/App&SceneDelegate/SceneDelegate.swift
> +        let networkService = NetworkService()
я не знаю, навіщо ти сюди взагалі додав роутер, але роутер точно нічого не має знати про network service

2023-11-13 14:10 UTC, Nikitax23 commented on NearestPlaces/Routing/Router.swift
> +
В даній реалізації цей роутер не потрібен. Тим паче, по факту він не показує екран, а просто сетить вью контроллери в навігейшн.

2023-11-13 14:10 UTC, Nikitax23 commented on NearestPlaces/Routing/Router.swift
> +    // MARK: - Properties -
після // MARK:  завжди треба ставити linebreak. щоб був один пустий рядок між маркою та кодом

2023-11-13 14:10 UTC, Nikitax23 commented on NearestPlaces/App&SceneDelegate/SceneDelegate.swift
> +        let navigationController = UINavigationController()
навігейшн можна ініціалізувати з вже готовим вью контролером

2023-11-13 14:10 UTC, Nikitax23 commented on NearestPlaces/App&SceneDelegate/SceneDelegate.swift
> +    func startRootScreen(for windowScene: UIWindowScene) {
функція має бути приватною

2023-11-13 14:10 UTC, Nikitax23 commented on NearestPlaces/Extensions/UINavigationController+Extension.swift
> +
зайвий лайнбрейк, який не потрібен тут.

2023-11-13 14:10 UTC, Nikitax23 commented on NearestPlaces/Extensions/UINavigationController+Extension.swift
> +
зайвий лайнбрейк

2023-11-13 14:10 UTC, Nikitax23 commented on NearestPlaces/Extensions/UINavigationController+Extension.swift
> +    func setNavigationControllerAppearance() {
я б в таком разі зробив це статичним, і викликав один раз на проект, якщо ти задаєш appearance. 
або якщо ти хочеш мати змогу задавати індивідуальні параметри для кожного навігейшна, тоді не треба через appearance робити.

2023-11-13 14:10 UTC, Nikitax23 commented on NearestPlaces/Extensions/UIViewController+Extension.swift
> +    typealias EmptyBlock = () -> Void
```
typealias EmptyBlock = () -> Void
    typealias AlertButtonAction = (title: String, completion: EmptyBlock?)
```

навіщо типу `UIViewController` мати ці тайпеліаси? Вони не належать `UIViewController`-у , то вони можуть лежати десь публічними константами у файлі публічних констант.

2023-11-13 14:10 UTC, Nikitax23 commented on NearestPlaces/Extensions/UIViewController+Extension.swift
> +            let alertAction = UIAlertAction(title: action.title, style: .default) { _ in
А що, якшо мені потрібна кнопка в екшні зі стайлом, який не `.default`? Наприклад, потрібна кнопка cancel або delete? Вони мають мати інший стиль. подумай про це

2023-11-13 14:10 UTC, Nikitax23 commented on NearestPlaces/Network/Endpoint.swift
> +    static let apiKey = Bundle.main.object(forInfoDictionaryKey: AppConstant.apiKeyGoogle) as! String
А якщо з `Bundle.main.object(forInfoDictionaryKey:)` не повернеться стрінг?

2023-11-13 14:10 UTC, Nikitax23 commented on NearestPlaces/Network/NetworkService.swift
> +private enum RequestError: Error {
Я б назвав це NetworkError , заміть RequestError

2023-11-13 14:10 UTC, Nikitax23 commented on NearestPlaces/Scenes/MapPlacesModule/Controllers/MapPlacesViewController.swift
> +    private let locationManager = CLLocationManager()
Краще створити власного `LocationService`, який буде мати приватний звʼязок з `CLLocationManager`, спілкуватися з делегатом, і надавати тільки потрібні івенти або колбеки до тих, хто ним користується.

2023-11-13 14:10 UTC, Nikitax23 commented on NearestPlaces/Scenes/MapPlacesModule/Controllers/MapPlacesViewController.swift
> +    private lazy var requestPlacesManuallyButton: UIBarButtonItem = {
`requestPlacesManuallyButton`
Не найкраща назва. Можна назвати `fetchButton`

2023-11-13 14:10 UTC, Nikitax23 commented on NearestPlaces/Scenes/MapPlacesModule/Controllers/MapPlacesViewController.swift
> +        title = Constant.navigationControllerTitle
```
title = Constant.navigationControllerTitle
        navigationItem.leftBarButtonItem = requestPlacesManuallyButton
```

Це варто винести у окремий метод `setupNavigationBar`

2023-11-13 14:10 UTC, Nikitax23 commented on NearestPlaces/Scenes/MapPlacesModule/Controllers/MapPlacesViewController.swift
> +    func isUserAuthorized() {
Це назва методу. Вона виглядає наразі, як назва булевої проперті. 
Для методу краще пасувала б назва `checkLocationPermissions` or `verifyLocationPermissions`

2023-11-13 14:10 UTC, Nikitax23 commented on NearestPlaces/Scenes/MapPlacesModule/Controllers/MapPlacesViewController.swift
> +        case.restricted, .denied:
треба додати пробіл

2023-11-13 14:10 UTC, Nikitax23 commented on NearestPlaces/Scenes/MapPlacesModule/Controllers/MapPlacesViewController.swift
> +            locationManager.requestWhenInUseAuthorization()
між кейсами можна додати лайнбрейки, для кращої читабельності: 

```
switch locationManager.authorizationStatus {
case .notDetermined: 
   locationManager.requestWhenInUseAuthorization()
   
case .authorizedAlways: 
   locationManager.startUpdatingLocation()
   
   ...
}
```

2023-11-13 14:10 UTC, Nikitax23 commented on NearestPlaces/Scenes/MapPlacesModule/Controllers/MapPlacesViewController.swift
> +        let camera = GMSCameraPosition.camera(withTarget: location, zoom: zoom)
Цей метод же не оновлює локацію юзера, правда? 
Він оновлює камеру та робить запит на додаткові елементи . То ж і називатися він має відповідно.

2023-11-13 14:10 UTC, Nikitax23 commented on NearestPlaces/Scenes/MapPlacesModule/Controllers/MapPlacesViewController.swift
> +    func loadPlaces(endpoint: Endpoint) {
краще `fetchPlaces` назвати

2023-11-13 14:10 UTC, Nikitax23 commented on NearestPlaces/Scenes/MapPlacesModule/Controllers/MapPlacesViewController.swift
> +    func loadPlaces(endpoint: Endpoint) {
і в принципі, цей метод може сам будувати ендпоінт і одразу ж звертатися до `networkService`. 
Не бачу сенсу в методі `requestPlacesWithLocation`

2023-11-13 14:10 UTC, Nikitax23 commented on NearestPlaces/Scenes/MapPlacesModule/Controllers/MapPlacesViewController.swift
> +    func showPlaceMarkers(for place: [PlaceInfo]) {
`func showPlaceMarkers(for place: [PlaceInfo])` => `func addMarkers(for places: [PlaceInfo])`

2023-11-13 14:10 UTC, Nikitax23 commented on NearestPlaces/Scenes/MapPlacesModule/Controllers/MapPlacesViewController.swift
> +                if !self.markersList.contains(place.name) {
А може таке бути, що назва буде однакова? Думаю, може. не варто полягати на назву місця, щоб ідентифікувати його.

2023-11-13 14:10 UTC, Nikitax23 commented on NearestPlaces/Scenes/MapPlacesModule/Controllers/MapPlacesViewController.swift
> +    func addPlaceMarker(for place: PlaceInfo) {
`func addPlaceMarker(for place: PlaceInfo)` дуже багато слів плейс в одному рядку. 
можна просто `addMarker(for place: PlaceInfo)`

2023-11-13 14:10 UTC, Nikitax23 commented on NearestPlaces/Scenes/MapPlacesModule/Controllers/MapPlacesViewController.swift
> +            DispatchQueue.global(qos: .background).asyncAfter(deadline: Constant.nextPageDelay) {
давай взагалі поки приберемо некст пейдж фічу з застосунку. в завданні цього не було, і не будемо наразі загострювати на цьому увагу.

2023-11-13 14:10 UTC, Nikitax23 commented on NearestPlaces/Scenes/MapPlacesModule/Controllers/MapPlacesViewController.swift
> +            if let appSettingsURL = URL(string: UIApplication.openSettingsURLString), UIApplication.shared.canOpenURL(appSettingsURL) {
```
if let appSettingsURL = URL(string: UIApplication.openSettingsURLString), UIApplication.shared.canOpenURL(appSettingsURL) {
                UIApplication.shared.open(appSettingsURL, options: [:])
            }
```

1) Краще це винести в окрему функцію. Я б навіть створив екстеншн для UIApplication і там статичну функцію.
2) Форматування варто покращити. перед `UIApplication.shared.canOpenURL` можна зробити лайнбрейк.

2023-11-13 14:10 UTC, Nikitax23 commented on NearestPlaces/Scenes/MapPlacesModule/Controllers/MapPlacesViewController.swift
> +
зайвий лайнбрейк на 232 рядку

2023-11-13 14:10 UTC, Nikitax23 commented on NearestPlaces/Network/Endpoint.swift
> +    static let defaultType = "restaurant|cafe"
протести будь ласка, прибираючи один з них, чи повертаються ті самі результати, чи ні? 
продебаж, зі списка елементів, які повертаються, чи там елементи різних типів, чи тільки одного?

2023-11-13 14:10 UTC, Nikitax23 commented on NearestPlaces/Scenes/MapPlacesModule/Model/Place.swift
> +struct Place: Codable {
`Codable` => `Decodable`, для всіх місць тут, які в тебе є наразі. 
Тобі ж не потрібно їх енкодити, правда?

2023-11-13 14:10 UTC, Nikitax23 commented on NearestPlaces/Scenes/MapPlacesModule/Model/Place.swift
> +        case nextPageToken = "next_page_token"
хоч ми і збираємось це видаляти, але `next_page_token` можна було добитися, заданням додаткового сеттінгзу для декодера. Не обовʼязково для цього створювати CodingKeys, якшо в тебе назви пропертей збігаються з назвою полів в ріспонсі (якщо тільки відрізняється camelCase та snake_case)

2023-11-13 14:10 UTC, Nikitax23 commented on NearestPlaces/Scenes/MapPlacesModule/Model/Place.swift
> +        name = try container.decodeIfPresent(String.self, forKey: .name) ?? ""
а навіщо нам такі дефолтні значення? 
якщо воно не прийшло, то воно не прийшло. треба обробляти опціоналами. В даному випадку це не є раціонально.

2023-11-13 14:10 UTC, Nikitax23 commented on NearestPlaces/Scenes/MapPlacesModule/Model/Place.swift
> +        icon = try container.decode(URL.self, forKey: .icon)
А чому ми декодимо URL тут? Тут варто декодити стрінгу

2023-11-13 14:10 UTC, Nikitax23 commented on NearestPlaces/Supporting/AppConstant.swift
> +    static let apiKeyGoogle = "API_KEY_GOOGLE"
навіщо ця константа видима на весь проект? вона ж нам не усюди потрібна?

2023-11-13 14:10 UTC, Nikitax23 commented on .gitignore
>  xcuserdata/
Чому в гітігнор додатий `Podfile.lock`? Він зберігає інформацію про версійність бібліотек, і має бути в репозиторії, щоб уникнути несподіваних змін версій бібліотек, після `pod install`.

2023-11-13 18:13 UTC, niestierov commented on NearestPlaces/Network/Endpoint.swift
> +    static let defaultType = "restaurant|cafe"
Тільки перший елемент. Перероблю на нову API.

2023-11-15 23:22 UTC, Nikitax23 requested changes
Гарні зміни, але ще треба попрацювати!

2023-11-15 23:22 UTC, Nikitax23 commented on NearestPlaces/App&SceneDelegate/AppDelegate.swift
Навіщо нам тут так багато пустих рядків?

2023-11-15 23:22 UTC, Nikitax23 commented on NearestPlaces/App&SceneDelegate/SceneDelegate.swift
> +        navigationController.setViewControllers([mapPlacesViewController], animated: true)
В цьому рядку немає сенсу. Ти вже задаєш `rootViewController: mapPlacesViewController` при ініціалізації навігейшна.

2023-11-15 23:22 UTC, Nikitax23 commented on NearestPlaces/Extensions/UIApplication+Extension.swift
> +        if let appSettingsURL = URL(string: UIApplication.openSettingsURLString),
А чи дійсно нам потрібен `completion` тут?
Ми збираємось якось обробляти результат?

2023-11-15 23:22 UTC, Nikitax23 commented on NearestPlaces/Extensions/UINavigationController+Extension.swift
> +    func setNavigationControllerAppearance(
Якщо ти вже пішов від Appearance, то треба вже і перейменувати назву методу.

2023-11-15 23:22 UTC, Nikitax23 commented on NearestPlaces/Extensions/UIViewController+Extension.swift
> +        static let defaultTryAgainAlertTitle = "There is an error."
`"There is an error."`
Виглядає трошки як зайве для тайтлу. 
Error було б достатньо. 

Та де ти бачив у тайтлах колись крапку в кінці?

2023-11-15 23:22 UTC, Nikitax23 commented on NearestPlaces/GoogleServicesConfigurator/GoogleServicesConfigurator.swift
> +    static let apiKeyGoogle = "API_KEY_GOOGLE"
`apiKeyGoogle` має бути приватною.

2023-11-15 23:22 UTC, Nikitax23 commented on NearestPlaces/Supporting/AppConstant.swift
> +typealias AlertButtonAction = (
```
typealias AlertButtonAction = (
    title: String,
    style: UIAlertAction.Style,
    completion: EmptyBlock?
)
typealias Alert = (
    title: String,
    message: String,
    actions: [AlertButtonAction]
)
```

1) Чому це , до речі, зроблено за допомогою Tuple та Typealias? Чому не структурами?
2) Намагайся уникати таких назв, які можуть конфліктувати з системними або з назвами компонентів в сторонніх бібліотеках.  `Alert` наприклад

2023-11-15 23:22 UTC, Nikitax23 commented on NearestPlaces/Scenes/MapPlacesModule/Controllers/MapPlacesViewController.swift
> +            static let whiteWithAlphaComponent = UIColor.white.withAlphaComponent(opacity)
Я таки не розумію. Ти збираєшся в кожному контролері дублювати такий енам і викликати той самий метод навігейшна?

2023-11-15 23:22 UTC, Nikitax23 commented on NearestPlaces/Scenes/MapPlacesModule/Controllers/MapPlacesViewController.swift
> +            static let whiteWithAlphaComponent = UIColor.white.withAlphaComponent(opacity)
Якщо так, але в тебе будуть однакові параметри для екранів, то це ідея не найкраща.

2023-11-15 23:22 UTC, Nikitax23 commented on NearestPlaces/Scenes/MapPlacesModule/Controllers/MapPlacesViewController.swift
> +        locationService.showAuthorizationDeniedAlert = { alert in
```
showTryAgainAlert
showAuthorizationDeniedAlert
```

1) Location Service - це сервіс. Він не знає про UI. Він не знає, що таке Алерт. Він може сказати "didChangeAuthorization" або ще щось. 
2) навіть якби назви були такі, які є, то треба коректно називати клоужери. наразі вони виглядають як функції,  які виконують якісь дії, а не є тригерами якихось дій (а хоча вони таки є тригерами). 
Наприклад, після виклику `locationService.showAuthorizationDeniedAlert` я вже очікую побачити алерт, а у нас йде ініціалізація клоужеру.

2023-11-15 23:22 UTC, Nikitax23 commented on NearestPlaces/Scenes/MapPlacesModule/Controllers/MapPlacesViewController.swift
> +    func locationService(_ locationService: LocationService, didUpdateLocation location: CLLocationCoordinate2D) {
навіщо нам тут потрібне `_ locationService: LocationService,` посилання на локейшн сервіс? ми і так знаємо, з яким сервісом ми спілкуємось. він в нас один. це зайве. 
І можна перейменувати метод на `didUpdateLocation` або `didReceiveLocation`

2023-11-15 23:22 UTC, Nikitax23 commented on NearestPlaces/LocationService/LocationService.swift
> +        enum Alert {
не думаю, що локейшн сервіс щось має знати про Алерт

2023-11-16 15:13 UTC, Nikitax23 approved these changes
Рухаємось далі! Молодець.

2023-11-16 15:13 UTC, Nikitax23 commented on NearestPlaces/Extensions/UIViewController+Extension.swift
> +    func showTryAgainAlert(
Я вважаю, що це не має бути частиною екстеншна `UIViewController`. 

Загальний (абстрактний) метод алерта - ок, але це вже деталі реалізації якісь. можна зібрати цей алерт там, де ти його будеш викликати, і викликати `showAlert` метод

2023-11-16 15:13 UTC, Nikitax23 commented on NearestPlaces/Extensions/UIViewController+Extension.swift
> +    func showTryAgainAlert(
Зробимо вже в наступному ПР.

2023-11-16 16:23 UTC, merged