Feature/list places
niestierov/NearestPlaces pull request #2
Opened 2023-11-19 09:43 UTC by niestierov

2023-11-20 12:35 UTC, Nikitax23 requested changes
Молодець. 
Залишив коменти для покращень. Працюємо!

2023-11-20 12:35 UTC, Nikitax23 commented on NearestPlaces/Extensions/Reusable+Extension.swift
> +protocol Reusable: AnyObject { }
Я б сказав, що краще назвати цей протокол `Identifiable` . Але так як у Swift є свій протокол з таким самим іменем, то можна назвати `StringIdentifiable`, наприклад . або `Describable`.

А твій протокол геть не має нічого, що описувало б Reusability

2023-11-20 12:35 UTC, Nikitax23 commented on NearestPlaces/Extensions/UITableView + Reusable.swift
> +            fatalError("cell of type \(cellType) not registered")
Можна залишити і так, але таким чином можна і обійтись просто 

```
dequeueReusableCell(
            withIdentifier: cellType.identifier,
            for: indexPath
        ) as! T
```

, що так само породить креш, у разі, якщо немає такого типу. Але єдине, що не буде цього меседжу , який є в фатал еррорі.

2023-11-20 12:35 UTC, Nikitax23 commented on NearestPlaces/Scenes/ListPlacesModule/Controller/Cell/ListPlaceTableViewCell.swift
> +class ListPlaceTableViewCell: UITableViewCell {
Клас має бути фінальним, якщо від нього не планується наслідування. 
Це покращить диспетчеризацію методів.

2023-11-20 12:35 UTC, Nikitax23 commented on NearestPlaces/Scenes/ListPlacesModule/Controller/Cell/ListPlaceTableViewCell.swift
> +    private let iconSVGView: UIImageView = {
`iconSVGView` навіщо нам тут абривіатура SVG? 
Це імедж вью, в ньому може бути будь-який тип, повʼязаний з картинками, не тільки SVG.

2023-11-20 12:35 UTC, Nikitax23 commented on NearestPlaces/Scenes/ListPlacesModule/Controller/Cell/ListPlaceTableViewCell.swift
> +        label.numberOfLines = .zero
`label.numberOfLines = .zero`

навіщо нам це тут? я не думаю, що для відображення рейтинга нам потрібен більше, ніж 1 рядок. Чи потрібен?

2023-11-20 12:35 UTC, Nikitax23 commented on NearestPlaces/Scenes/ListPlacesModule/Controller/Cell/ListPlaceTableViewCell.swift
> +        nameLabel.text = Constant.Title.name + name
це краще розбити по окремим лейблам, замість конкатинації стрінгів.

2023-11-20 12:35 UTC, Nikitax23 commented on NearestPlaces/Scenes/ListPlacesModule/Controller/Cell/ListPlaceTableViewCell.swift
> +        let rating = String(place.rating ?? .zero)
Для приведення типів можна створити екстеншн, який буде робити цю саму дію для потрібного типу. 

Наприклад, ти зможеш потім викликати `place.rating.stringValue()` або `place.rating.stringValue`

2023-11-20 12:35 UTC, Nikitax23 commented on NearestPlaces/Scenes/ListPlacesModule/Controller/Cell/ListPlaceTableViewCell.swift
> +    func buildIconURL(string icon: String) -> URL? {
```
func buildIconURL(string icon: String) -> URL? {
        let iconFullUrlString = icon + Constant.iconType

        guard let url = URL(string: iconFullUrlString) else {
            return nil
        }

        return url
    }

    func setIconImage(string icon: String) {
        let iconUrl = buildIconURL(string: icon)

        if let iconUrl {
            self.iconSVGView.kf.setImage(with: iconUrl)
        } else {
            self.iconSVGView.image = UIImage(systemName: Constant.placeholderIconImage)
        }
    }
```

Ти можеш створити якийсь ImageService / ImageManager , який буде мати 1) універсальний метод задавання картинки по урл (буде викликати Кінгфішер, та обробляти результат). 2) Буде мати метод, який просто приймає твій iconUri , там сам будувати урл та задавати імедж в результаті, використовуючи метод 1. 
Потім можна 
або 
-  створити екстеншн для `UIImageView`, який буде звертатися до твого сервісу та викликати його, щоб задати імедж в себе. 

або 
- передавати в твій сервіс `UIImageView` інстанс, в який буде безспосередньо задаватися картинка.

2023-11-20 12:35 UTC, Nikitax23 commented on NearestPlaces/Scenes/ListPlacesModule/Controller/Cell/ListPlaceTableViewCell.swift
> +            self.iconSVGView.image = UIImage(systemName: Constant.placeholderIconImage)
плейсхолдер, до речі, можна буде теж туди задавати в той метод, опціонально.

2023-11-20 12:35 UTC, Nikitax23 commented on NearestPlaces/Scenes/ListPlacesModule/Controller/Cell/ListPlaceTableViewCell.swift
> +    // MARK: - Iternal -
`Iternal`

Помилка в слові

2023-11-20 12:35 UTC, Nikitax23 commented on NearestPlaces/Scenes/ListPlacesModule/Controller/Cell/ListPlaceTableViewCell.swift
> +    // MARK: - LifeCycle -
`LifeCycle` Life Cycle - це два окремих слова.

2023-11-20 12:35 UTC, Nikitax23 commented on NearestPlaces/Scenes/ListPlacesModule/Controller/Cell/ListPlaceTableViewCell.swift
> +    // MARK: - UIComponents -
`UIComponents` - це два окремих слова

2023-11-20 12:35 UTC, Nikitax23 commented on NearestPlaces/Scenes/ListPlacesModule/Controller/Cell/ListPlaceTableViewCell.swift
> +class ListPlaceTableViewCell: UITableViewCell {
`ListPlaceTableViewCell` => `PlaceListTableViewCell `

2023-11-20 12:35 UTC, Nikitax23 commented on NearestPlaces/Scenes/ListPlacesModule/Controller/ListPlacesViewController.swift
> +    // MARK: - UIComponents -
ті ж самі коменти по марках (зроби усюди, плз)

2023-11-20 12:35 UTC, Nikitax23 commented on NearestPlaces/Scenes/ListPlacesModule/Controller/ListPlacesViewController.swift
> +        navigationController?.isNavigationBarHidden = false
`navigationController?.isNavigationBarHidden = false`

Навіть для цього я б створив метод `setupNavigationBar`

2023-11-20 12:35 UTC, Nikitax23 commented on NearestPlaces/Scenes/ListPlacesModule/Controller/ListPlacesViewController.swift
> +        return UITableView.automaticDimension
це можна задати в твоїй lazy var

2023-11-20 12:35 UTC, Nikitax23 commented on NearestPlaces/Scenes/ListPlacesModule/Controller/ListPlacesViewController.swift
> +    private var tableView: UITableView = {
краще UI елементи позначати, як `lazy var`. Тоді цей код буде виконуватись тільки тоді, коли він потрібен, і не витрачати ресурс компілятора задарма. Гарна практика.

2023-11-20 12:35 UTC, Nikitax23 commented on NearestPlaces/Scenes/ListPlacesModule/Controller/Cell/ListPlaceTableViewCell.swift
> +    private let addressLabel: UILabel = {
краще створювати юай елементи `lazy var`-ами

2023-11-20 12:35 UTC, Nikitax23 commented on NearestPlaces/Scenes/MapPlacesModule/Controllers/MapPlacesViewController.swift
> +        button.layer.cornerCurve = .continuous
```
button.layer.cornerCurve = .continuous
        button.backgroundColor = .white
        button.tintColor = .darkGray
        button.layer.shadowColor = UIColor.black.cgColor
        button.layer.shadowOpacity = 0.3
        button.layer.shadowOffset = CGSize(width: 0, height: 2)
        button.layer.shadowRadius = 2
```

Варто створити екстеншн для `UIView`, який буде приймати це все параметрами, та буде перевикористовуватися всіми нащадками UIView . І тоді вже тут перевикористовувати це.

2023-11-20 12:35 UTC, Nikitax23 commented on NearestPlaces/Scenes/MapPlacesModule/Controllers/MapPlacesViewController.swift
> +        navigationController?.isNavigationBarHidden = true
те ж саме тут про метод `setupNavigationBar`

2023-11-20 12:35 UTC, Nikitax23 commented on NearestPlaces/Scenes/MapPlacesModule/Controllers/MapPlacesViewController.swift
> +        let cornerRadius = listPlacesButton.frame.size.width / 2
це можна робити в `lazy var `. 
для задання корнер радіуса теж треба створити екстеншн для `UIView`.

2023-11-20 12:35 UTC, Nikitax23 commented on NearestPlaces/Scenes/MapPlacesModule/Controllers/MapPlacesViewController.swift
> +    @objc func routeToListPlaces() {
`routeToListPlaces` => `showPlacesList`

2023-11-20 12:35 UTC, Nikitax23 commented on NearestPlaces/Scenes/MapPlacesModule/Controllers/MapPlacesViewController.swift
> +    @objc func routeToListPlaces() {
Route тут є некоретним, з точки зору англійської та з точки зору логіки найменування.

2023-11-20 12:35 UTC, Nikitax23 commented on NearestPlaces/Scenes/ListPlacesModule/Controller/Cell/ListPlaceTableViewCell.swift
> +        setIconImage(string: iconString)
з високою вірогідністю в тебе буде баг, що буде показувати невалідні іконки для деяких комірок. 
наприклад, в комірці 1 буде відображатися іконка, яка має бути в комірці 5. і тд. 
Подумай, чому, і що можна з цим зробити.

2023-11-21 13:29 UTC, Nikitax23 requested changes
Майже там! Ще трошки покращимо.

2023-11-21 13:29 UTC, Nikitax23 commented on NearestPlaces/Extensions/Double+Extension.swift
> +        return String(describing: self)
малось на увазі не `String(describing: self)` , а приведення типу `return String(format: "%.1f", self)`

2023-11-21 13:29 UTC, Nikitax23 commented on NearestPlaces/Extensions/UITableView + Reusable.swift
> +        let cell = dequeueReusableCell(
можна спростити до 

```
return dequeueReusableCell(
            withIdentifier: cellType.identifier,
            for: indexPath
        ) as! T
```

2023-11-21 13:29 UTC, Nikitax23 commented on NearestPlaces/Extensions/UIView+Extension.swift
> +    func configure(
так як цей метод безпосередньо займається заданням тіні, то не варто називати метод configure. Ми ж не конфігуруємо, ми задаємо тінь. 
Бекграунд колор тут - це зайве. Це не має ніякого відношення до даного методу. 

Метод можна назвати `applyShadow` або `addShadow`

2023-11-21 13:29 UTC, Nikitax23 commented on NearestPlaces/Extensions/UIView+Extension.swift
> +    func setCornerRadius(
Це звісно прикольно, але також рекомендую створити property з геттером та сеттером { get set }. 

Щоб можна було задати простий корнер радіус. 

Так само, це можна буде перевикористати тут, в цьому методі, якщо він тобі потрібен.

2023-11-21 13:29 UTC, Nikitax23 commented on NearestPlaces/Extensions/UIView+Extension.swift
> +    func setCornerRadius(
Також, зазвичай треба задавати `masksToBounds` або `clipToBounds`. Не знаю, як в тебе без цього працює. Може щось змінилось у Swift.

2023-11-21 13:29 UTC, Nikitax23 commented on NearestPlaces/Extensions/UIView+Extension.swift
> +    func setCornerRadius(
https://stackoverflow.com/questions/27861383/how-to-set-corner-radius-of-imageview

2023-11-21 13:29 UTC, Nikitax23 commented on NearestPlaces/ImageService/ImageService.swift
> +    static let shared = ImageService()
треба робити init приватним, щоб заблокувати можливість інітити інстанси даного типу.

2023-11-21 13:29 UTC, Nikitax23 commented on NearestPlaces/ImageService/ImageService.swift
> +        guard let url = URL(string: string + type) else {
`URL(string: string + type)`

ненадійний варіант, тому що ти довіряєш розстановку "/" зовнішнім чинникам (реалізації). Це має вирішуватися тут, в таком разі.

2023-11-21 13:29 UTC, Nikitax23 commented on NearestPlaces/ImageService/ImageService.swift
> +        guard let url = URL(string: string + type) else {
Також має бути метод , який приймає урл стрінг та плейсхолдер, але не привʼязаний до твого type. Тобто, який за дефолтом з урл стрінги будує одразу урл (без додаткової логіки)

2023-11-21 13:29 UTC, Nikitax23 commented on NearestPlaces/ImageService/ImageService.swift
> +        guard let url = URL(string: string + type) else {
і тут його можна буде перевикористовувати

2023-11-21 13:29 UTC, Nikitax23 commented on NearestPlaces/Scenes/ListPlacesModule/Controller/Cell/PlaceListTableViewCell.swift
> +        DispatchQueue.main.async {
`DispatchQueue.main.async` це можна покласти в імедж сервіс, в якому безпосередьно задається картинка після завантаження

2023-11-21 13:29 UTC, Nikitax23 commented on NearestPlaces/Scenes/ListPlacesModule/Controller/Cell/PlaceListTableViewCell.swift
> +        DispatchQueue.main.async {
щоб кожен раз в кожному місці це не викликати

2023-11-21 13:29 UTC, Nikitax23 commented on NearestPlaces/Scenes/ListPlacesModule/Controller/PlacesListViewController.swift
> +        table.estimatedRowHeight = UITableView.automaticDimension
є прям проперті rowHeight

приклад: 

```
tableView.estimatedRowHeight = 80
tableView.rowHeight = UITableView.automaticDimension
```

2023-11-21 13:29 UTC, Nikitax23 commented on NearestPlaces/Extensions/UIImageView+Extension.swift
> +    func setImage(with urlString: String, type: String, placeholder: UIImage? = nil) {
неочевидно і незрозуміло, що таке type. 
Краще не тягнути цю логіку взагалі в абстракцію (екстеншн чи імедж сервіс), краще будувати це ззовні, і просто передавати в абстракцію готовий урл стрінг. Без деталей реалізації.

2023-11-21 14:51 UTC, niestierov commented on NearestPlaces/Extensions/UIView+Extension.swift
> +    func setCornerRadius(
При

> Також, зазвичай треба задавати `masksToBounds` або `clipToBounds`. Не знаю, як в тебе без цього працює. Може щось змінилось у Swift.

якщо задати одну з цих проперті, то тіні не буде видно

2023-11-21 15:01 UTC, Nikitax23 requested changes
І ще пара моментів. Працюємо.

2023-11-21 15:01 UTC, Nikitax23 commented on NearestPlaces/Extensions/UIView+Extension.swift
> +            return self.layer.cornerRadius
1) self можна усюди опустити усюди в цьому екстеншні (немає необхідності вказувати це тут). 
2) чому маскування / обрізання to bounds не задаєш?

2023-11-21 15:01 UTC, Nikitax23 commented on NearestPlaces/ImageService/ImageService.swift
> +            DispatchQueue.main.async {
```
DispatchQueue.main.async {
                imageView.image = placeholder
            }
```

тут немає сенсу вкладати це в `DispatchQueue.main.async`. Який сенс, якщо це синхронне задання вже існуючої картинки, і ми не йшли на іншу чергу чи потік ?

2023-11-21 15:01 UTC, Nikitax23 commented on NearestPlaces/Scenes/ListPlacesModule/Controller/Cell/PlaceListTableViewCell.swift
> +        iconImageView.kf.cancelDownloadTask()
```
iconImageView.kf.cancelDownloadTask()
        iconImageView.image = nil
```

До речі, існує рекомендація, що краще це робити на моменті cellForRow (тобто в твоєму `configure` методі).
https://developer.apple.com/documentation/uikit/uitableviewcell/1623223-prepareforreuse

2023-11-22 12:03 UTC, Nikitax23 approved these changes
Виправ єдиний комент і мержи.

2023-11-22 12:03 UTC, Nikitax23 commented on NearestPlaces/Scenes/ListPlacesModule/Controller/Cell/PlaceListTableViewCell.swift
> +        iconImageView.image = nil
Це теж треба перенести туди ж, де і кенселиш завантаження

2023-11-22 15:54 UTC, Nikitax23 commented on NearestPlaces/Scenes/ListPlacesModule/Controller/Cell/PlaceListTableViewCell.swift
> +        label.textColor = .label
Намагайся не використовувати системні кольори. `.label` - це системний колір.

2023-11-22 15:54 UTC, Nikitax23 commented on NearestPlaces/Services/ImageService/ImageService.swift
> +                    imageView.image = value.image.withTintColor(.label)
`.label` - це системний колір

2023-11-24 08:50 UTC, merged